name: adaptive_navbar

description: An Adaptive Navigation Bar in flutter. Depending on the screen width, this navbar changes itself into a menu icon in mobile view and navbar in web view.

version: 0.0.3

# author: Mouli Bheemaneti <moulibheemaneti99@gmail.com>

homepage: https://github.com/moulibheemaneti/adaptive_navbar.git

repository: https://github.com/moulibheemaneti/adaptive_navbar.git

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
